# Generated by Django 4.2.3 on 2023-08-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_for_admin', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(max_length=6)),
                ('can_rename', models.BooleanField(max_length=6)),
            ],
        ),
    ]
