# Generated by Django 4.2.3 on 2023-09-27 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ship_game', '0002_room_alter_player_can_rename_player_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='unknown_player_hash_list',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.CreateModel(
            name='RoomPlayerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship_game.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship_game.room')),
            ],
            options={
                'unique_together': {('player', 'room')},
            },
        ),
    ]
