# Generated by Django 4.2.3 on 2023-09-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_game', '0003_remove_player_room_room_unknown_player_hash_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='unknown_player_hash_list',
            new_name='unknown_player_token_list',
        ),
    ]
