# Generated by Django 4.2.3 on 2023-09-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_game', '0004_rename_unknown_player_hash_list_room_unknown_player_token_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
